name: conda-flask-base
channels:
- defaults
dependencies:
- python=3.5.4=0
- pip:
    - flask
    - pytest
    - pytest-flask
    - Flask-RESTful
    - Flask-JWT
    - flask-bcrypt
    - requests
    - scrapy
    - sqlalchemy
